contracts/swaggerV1Compat.yml
scripts/test-oats.sh

Fixes #28 
This also fixes a quickly addressable bug surfaced while extending the tests.

fix: extend basic oats verification to other definitions

---

contracts/cli.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
src/cli.yml
src/common/paths/write.yml

Pretty straightforward.
I added `format: byte` to the request body to hint to codegen that it should use `[]byte` instead of `string`, which simplified porting the `influx write` command to the new repo.

feat: add /write API to CLI contract

---

contracts/cli.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
src/cli.yml
src/common/_schemas.yml
src/common/paths/buckets.yml
src/common/paths/buckets_bucketID.yml
src/common/schemas/PatchBucketRequest.yml
src/common/schemas/PatchRetentionRule.yml
src/common/schemas/PatchRetentionRules.yml

This required a fix to the spec for the update-bucket API. The previous spec was using `Bucket` as the request body, but that was wrong because:
* Some fields in `Bucket` can't be updated and aren't "seen" by the server-side API implementation
* Things marked as required in `Bucket` aren't necessarily required in update requests

feat: extend CLI contract enough to implement `influx bucket` commands

---

contracts/cli.yml
contracts/cloud-diff.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.yml
contracts/priv/cloud-priv.yml
src/cli.yml
src/cloud.yml
src/cloud/paths/measurements.yml
src/cloud/paths/measurements_measurementID.yml
src/cloud/schemas/ColumnDataType.yml
src/cloud/schemas/ColumnSemanticType.yml
src/cloud/schemas/MeasurementSchema.yml
src/cloud/schemas/MeasurementSchemaColumn.yml
src/cloud/schemas/MeasurementSchemaCreateRequest.yml
src/cloud/schemas/MeasurementSchemaList.yml
src/cloud/schemas/MeasurementSchemaUpdateRequest.yml
src/common/_schemas.yml
src/common/schemas/Bucket.yml
src/common/schemas/PostBucketRequest.yml
src/common/schemas/SchemaType.yml

This PR introduces Cloud 2 specific APIs for managing explicit schema buckets. Most of the changes are in the `cloud`
source tree, as the feature is Cloud 2 only.
The `Bucket` type adds a `schemaType` property. 
* For OSS it is expected to return `implicit`. 
* For Cloud 2 it can be either `implicit` or `explicit`, once the feature is available.

feat: Add explicit schema bucket APIs

---

contracts/cloud-diff.yml
contracts/cloud.yml
contracts/priv/cloud-priv.yml
src/cloud/schemas/Resource.yml

Adding functions as a resource type in order for the user to create tokens to access reading/writing functions.

chore: add functions as a resource type

---

contracts/oss-diff.yml
contracts/oss.yml
src/oss.yml

Closes #31 
Specified different URL for `/health` and `/ready` via `servers` property.

fix: adding servers property for /health and /ready (#31)

---

contracts/oss-diff.yml
contracts/oss.yml
src/common/paths/users.yml

Related to https://github.com/influxdata/influxdb/pull/21367
Related to https://github.com/influxdata/influxdb-client-csharp/issues/190
List users via the API now supports offset, limit or after parameter.

feat(oss): list users via the API now supports `offset`, `limit` or `after` parameter

---

contracts/cli.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cli.yml
src/common/_schemas.yml
src/common/paths/orgs.yml
src/common/paths/orgs_orgID.yml
src/common/schemas/PatchOrganizationRequest.yml
src/common/schemas/PostOrganizationRequest.yml

Similar to changes made in #36, the spec for patch-/post-ing buckets was reusing the `Organization` schema even though those APIs don't support specifying / overwriting all of the fields that can be in an org.

fix: use separate models for org POST and PATCH to match actual impl

---

contracts/cli.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/buckets_bucketID_members.yml
src/common/paths/buckets_bucketID_members_userID.yml
src/common/paths/buckets_bucketID_owners.yml
src/common/paths/buckets_bucketID_owners_userID.yml
src/common/paths/dashboards_dashboardID_members.yml
src/common/paths/dashboards_dashboardID_members_userID.yml
src/common/paths/dashboards_dashboardID_owners.yml
src/common/paths/dashboards_dashboardID_owners_userID.yml
src/common/paths/orgs_orgID_members.yml
src/common/paths/orgs_orgID_members_userID.yml
src/common/paths/orgs_orgID_owners.yml
src/common/paths/orgs_orgID_owners_userID.yml
src/common/paths/scrapers_scraperTargetID_members.yml
src/common/paths/scrapers_scraperTargetID_members_userID.yml
src/common/paths/scrapers_scraperTargetID_owners.yml
src/common/paths/scrapers_scraperTargetID_owners_userID.yml
src/common/paths/tasks_taskID_members.yml
src/common/paths/tasks_taskID_members_userID.yml
src/common/paths/tasks_taskID_owners.yml
src/common/paths/tasks_taskID_owners_userID.yml
src/common/paths/telegrafs_telegrafID_members.yml
src/common/paths/telegrafs_telegrafID_members_userID.yml
src/common/paths/telegrafs_telegrafID_owners.yml
src/common/paths/telegrafs_telegrafID_owners_userID.yml

Some codegen tools use `tags` to group generated components. The openapi-tools generator produces duplicate outputs for routes that are tagged twice.

fix: remove Users tag from APIs that have another tag

---

contracts/priv/unity.yml
src/unity/paths/usage_vectors.yml
src/unity/schemas/Invites.yml
src/unity/schemas/Invoices.yml
src/unity/schemas/UsageVectors.yml
src/unity/schemas/Users.yml

Initial definitions for routes that return one array of objects were set-up to nest the array within an object: 
Example: 
```
{
"invites": [
{
"id": "string",
"email": "string",
"role": "member",
"expiresAt": "2021-05-17T18:09:57.289Z",
"required": "string"
}
]
}
```
However for consistency with OEM api we are removing the nesting, so the new response for applicable routes will be:
```
{
[
{
"id": "string",
"email": "string",
"role": "member",
"expiresAt": "2021-05-17T18:09:57.289Z",
"required": "string"
}
]
}
```
Effected routes are: 
- `GET /billing/invoices`
- `GET /usage/vectors`
- `GET /orgs/{orgId}/users`
- `GET /orgs/{orgId}/invites`

fix(unity): remove response nesting for paths that return one array

---

contracts/priv/unity.yml
src/unity/paths/usage_vector_name.yml

Quartz handles `writes` as `writes_mb`, so the list of allowed `vector_name` was updated to reflect `writes_mb`.

fix(unity): update vector name to match backend

---

contracts/priv/unity.yml
src/unity/paths/usage_rate_limits.yml
src/unity/paths/usage_vector_name.yml

Defined specific errors for `GET /usage/rate_limits` and added a missing definition for `GET /usage/{vector_name}`. 
-400: invalid query param name
-401: unauthorized 
-404: invalid path param; user/org not found

fix(unity): add error definition to usage rate limits

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/delete.yml

This helps codegen systems name the generated API intelligently. Without the tag it ends up in a "default" bucket.

Add a tag to the PostDelete operation.

---

contracts/cloud-diff.yml
contracts/cloud.yml
contracts/common.yml
contracts/managed-functions.yml
contracts/mapsd.yml
contracts/oss-diff.yml
contracts/oss.yml
contracts/priv/annotationd.yml
contracts/priv/cloud-priv.yml
contracts/priv/notebooksd.yml
contracts/priv/quartz-oem.yml
contracts/priv/unity.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/svc/annotationd.yml
contracts/svc/managed-functions.yml
contracts/svc/mapsd.yml
contracts/svc/notebooksd.yml
src/common/schemas/ErrorCode.yml

Quartz is going to return a 415 unsupported media type when the content type is not supported. It looks like IDPE translates unsupported media type to invalid, but this will likely be updated in the future.

feat: add unsupported media type as error code

---

contracts/priv/unity.yml
src/unity/paths/usage_billing_stats.yml

Add error response definition to `GET /usage/billing_stats`.

fix(unity): add error definition to usage billing stats route

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/TableViewProperties.yml

Adds `type: object` to `tableOptions` schema. Without `type`, openapi generator produces incorrect / unusable code for some languages.

fix: add tableOptions type

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/DateTimeLiteral.yml

The `DateTimeLiteral` should be specified  with `format` property as a `date-time`. It is useful for generated client because the property will be defined as a `DateTime` not `String`.
- https://github.com/influxdata/flux/blob/eb2e578d5af6fc5a6f4a3f8a0ec0a640506f7b1d/ast/ast.go#L1738
- https://swagger.io/docs/specification/data-models/data-types/#format

feat: specify date format for DateTimeLiteral

---

contracts/priv/unity.yml
src/unity/paths/payment_form.yml
src/unity/paths/usage_rate_limits.yml
src/unity/paths/usage_vector_name.yml
src/unity/schemas/Account.yml
src/unity/schemas/BillingContact.yml
src/unity/schemas/BillingDate.yml
src/unity/schemas/BillingInfo.yml
src/unity/schemas/BillingNotifySettings.yml
src/unity/schemas/CreditCardParams.yml
src/unity/schemas/Invite.yml
src/unity/schemas/Invoice.yml
src/unity/schemas/Marketplace.yml
src/unity/schemas/Me.yml
src/unity/schemas/Organization.yml
src/unity/schemas/PaymentMethod.yml
src/unity/schemas/Region.yml
src/unity/schemas/RelatedAccount.yml
src/unity/schemas/UsageVector.yml
src/unity/schemas/User.yml

Previously generate types were setting `required` as an optional parameter rather than having the nested parameters be required.
In addition, the `enums` in the paths weren't listing an enum, but were rather simply saying that the parameter was a string

chore: updated spacing and enum format to make generated types and stuff check out

---

contracts/priv/unity.yml
src/unity/schemas/Invite.yml

The reason we aren't making the `id` property required is because when we create the invite, the ID hasn't been generated yet

chore: updating the strictness of invites

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/NotificationRuleBase.yml

The `id` of `NotificationRuleBase` should not be required property.
The `NotificationRuleBase` schema is also used for creating `NotificationRules` via inheritance.
https://github.com/influxdata/openapi/blob/1c8992412d666deec3522c5dae6dedec85c294e4/src/common/paths/notificationRules.yml#L41
PostNotificationRule > NotificationRuleDiscriminator > SlackNotificationRule > NotificationRuleBase

fix: id of NotificationRuleBase is not required

---

contracts/priv/unity.yml
src/unity/schemas/User.yml

The schema for user looked like the response expected for the operator type user response rather than the regular users page user response. At this point, there is no api for the users in the unity swagger so rather than creating a OperatorUser and User, we just updated User since that schema is only being used by the `GET /orgs/{orgId}/users` endpoint.

chore(unity): update user schema to match quartz api

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/NotificationRuleBase.yml

If the NotificationRule is created without `tagRules`:
```console
-> POST
-> /api/v2/notificationRules
{
"type": "slack",
"messageTemplate": "${ r._message }",
"endpointID": "0794dbceee052000",
"orgID": "e528f835bc53a6ec",
"status": "active",
"name": "Critical status to Slack_2021-05-25 14:13:37.518816",
"every": "10s",
"offset": "0s",
"tagRules": [],
"statusRules": [{
"currentLevel": "CRIT"
}]
}
```
the response doesn't contains `tagRules` tag:
```console
<- 201 Created
{
"id": "0794dbcef03f9000",
"name": "Critical status to Slack_2021-05-25 14:13:37.518816",
"endpointID": "0794dbceee052000",
"orgID": "e528f835bc53a6ec",
"ownerID": "0794db2e1f852000",
"every": "10s",
"offset": "0s",
"runbookLink": "",
"statusRules": [{
"currentLevel": "CRIT",
"previousLevel": null
}],
"createdAt": …
```

chore: updating the strictness of NotificationRuleBase

---

src/oss/paths/backup_metadata.yml
src/oss/paths/backup_shards_shardID.yml
src/oss/schemas/MetadataBackup.yml
src/oss/schemas/ShardMetadataManifest.yml
src/oss/schemas/ShardMetadataManifests.yml

Closes #96
There are 2 routes here:
* `backup_metadata.yml` describes a new route we plan to implement for OSS 2.1
* `backup_shards_shardID.yml` describes an existing route in OSS 2.0.x that we plan to keep
I haven't added either to `src/oss.yml` yet because we haven't implemented the new API. I wanted to merge this first so we could work on the CLI pieces in parallel.

Add specs for OSS 2.1 backup APIs

---

contracts/priv/unity.yml
src/unity/schemas/Invoice.yml

To fix a bug involving invoices, the api needs to use the id of the invoice rather than the id of the invoice pdf file.

feat(unity): update invoice to have id instead of filesId

---

contracts/priv/unity.yml
src/unity/paths/marketplace.yml
src/unity/schemas/Marketplace.yml

Remove `status` and `subscriberId` since they are relevant to the marketplace subscription and not the marketplace.
Add error definitions for `GET /marketplace`

chore(unity): add error definitions for /marketplace

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/Query.yml

Define `Query params` as a dictionary.
- https://swagger.io/docs/specification/data-models/dictionaries/

chore: Query params as a dictionary

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/common/schemas/Resource.yml

The InfluxDB OSS has also `notebooks` permission resource type:
https://github.com/influxdata/influxdb/blob/40897b9a98fe48834bf2a6a9469aae89f85a0d33/authz.go#L139

chore: add `notebooks` permission resource

---

contracts/priv/unity.yml
src/unity/schemas/BillingContact.yml

Update the Unity swagger for `PUT billing/contact` to remove requirement for `street1` in request body and changed type for `postalCode` from `number` to `string` because not all postal codes are comprised solely of numbers.

fix(unity): update requirements and schema for `PUT billing/contact`

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/TelegrafPlugin.yml

The type of TelegrafPlugin can be:
- inputs
- outputs
- aggregators
- processors

chore: specify possible types for TelegrafPlugin

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/StaticLegend.yml

As part of https://github.com/influxdata/ui/issues/1666
On the backend, static legend's properties must always be tracked. For `hide` there are really 3 states: true, false, and not set.
This is different than on the frontend, where Giraffe sees a lack of a "static legend" object to mean that static legend is not desired. And static legend's hide property is for convenience; it is a way to temporarily hide the static legend without removing (and later rebuilding) the entire object. Thus it is the static legend object itself that is analogous to the backend's `hide` property -- and has 3 states: staticLegend.hide is true, staticLegend.hide is false, and the lack of staticLegend.
Thus, on the backend we should change `hide` to `show` to accurately reflect "not set" to be the same as false.

fix: change static legend's hide property to show

---

.circleci/config.yml
Makefile
contracts/ref/cloud.yml
contracts/ref/oss.yml
scripts/ci-swagrag.dockerfile
scripts/oats.dockerfile
scripts/reference.sh
scripts/swagger-cli.dockerfile

previously, the circle tests were assumed to be using `make test` to verify the reference contracts were in sync, this adds a step in the circle job to validate ref contracts.

fix: actually run test to verify reference contract was generated

---

src/common/schemas/LineProtocolError.yml
src/common/schemas/LineProtocolErrorCode.yml
src/common/schemas/LineProtocolLengthError.yml
src/common/schemas/LineProtocolLengthErrorCode.yml

This helps some codegen systems generate true enums.
I thought about reusing the existing `ErrorCode` enum, but the possible values weren't a 1:1 match.

Split out enums for line-protocol error codes.

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/TelegrafPlugin.yml

Reverts influxdata/openapi#116
This PR is reverting a telegraf plugin type definition since there's a discrepancy between the UI declared type and the new contract definition that's leaving a bit of confusion surrounding which source of truth needs to be updated (the yaml to accommodate the UI-declared types or the UI to conform to new API changes as per the above yaml changes).

revert: "chore: specify possible types for TelegrafPlugin"

---

contracts/priv/annotationd.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/svc/annotationd.yml
src/svc/annotationd/paths/annotations.yml
src/svc/annotationd/paths/streams.yml

closes #111
The 404 when listing may or may not be desired, but i won't remove it unless someone feels we should just return an empty slice. currently a 404 will be returned when the filter parameters result in 0 annotations/streams being found (for `/annotations` and `/streams`

chore: remove typo error code from annotations api

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/Template.yml
src/common/schemas/TemplateEntry.yml
src/common/schemas/TemplateExportByID.yml
src/common/schemas/TemplateExportByName.yml

The API said the `resources` field of template-export request bodies should be an `object`, but both [OSS](https://github.com/influxdata/influxdb/blob/master/pkger/http_server_template.go#L74) and [Cloud](https://github.com/influxdata/idpe/blob/e4b817915e56e71fa558bb875699b147f5c70811/influxdbv2/pkger/http_server_template.go#L73) expect it to be an array of objects.

Fix schema for template-export request

---

contracts/priv/unity.yml
src/unity/paths/operator_accounts_accountId.yml

As part of [Quartz #4765](https://github.com/influxdata/quartz/issues/4765), `404` has been removed from error definitions. In current functionality, the lack of account doesn't make it impossible to return a `204` for the `DELETE` request, per @randycoulman.

fix(unity): remove 404 for operator delete account

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/LatLonColumn.yml
src/common/schemas/LatLonColumns.yml

LatLonColumns' lat and lon properties are required in giraffe yet optional in openapi yml files. This fixes that issue

fix: types for LatLonColumns to match the ones in giraffe

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/_schemas.yml
src/common/paths/dbrps.yml
src/common/paths/dbrps_dbrpID.yml
src/common/schemas/DBRP.yml
src/common/schemas/DBRPCreate.yml
src/common/schemas/DBRPGet.yml
src/common/schemas/DBRPUpdate.yml
src/common/schemas/DBRPUpdateResponse.yml

Related to https://github.com/influxdata/influx-cli/issues/24
This PR updates the swagger definition with the `v1dbrps` endpoint to more accurately reflect its usage, and allow for CLI code to be generated off of the swagger spec.
There were generally some mismatches between the form of responses and the types of parameters needed from requests that are being corrected with this PR.

fix: corrections for v1 dbrp api definition

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/sso.yml

Add a connection route so that we can provide it `email` parameter and retrieve its corresponding SSO connection.

chore: add connection route

---

contracts/priv/unity.yml
src/unity/paths/sso.yml

The response type for sso connection api request needs to be application/json even though the response is actually a JSON encoded string. So, we aren't going to have a schema instead we will have the response as `application/json` and the schema type will be `string`.

chore: update response type

---

contracts/priv/unity.yml
src/unity/paths/operator_accounts_accountId_users_userId.yml

As noted in [Quartz #4766](https://github.com/influxdata/quartz/issues/4766), the `404` error for users that don't exist/already deleted is being removed. API will simply return `204` if either of those cases are encountered.

fix(unity): Remove 404 from Operator delete user api definition

---

contracts/priv/unity.yml
src/unity/paths/operator_orgs_orgId.yml
src/unity/schemas/Organization.yml
src/unity/schemas/RelatedAccount.yml

As part of [#4767](https://github.com/influxdata/quartz/issues/4767) I found that the current api response does not line up to the swagger definition. This updates the swagger to be in line with the response.

feat(operator-orgs): Update operator/orgs GET to reflect api response

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/legacy_authorizations_authID_password.yml

Fixes the V1 Auth password parameter being a query parameter instead of a request body. Also fixes it using `patch` instead of `post`

fix: v1 auth taking password as query instead of requestBody

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/legacy_authorizations.yml
src/oss/paths/legacy_authorizations_authID.yml
src/oss/paths/legacy_authorizations_authID_password.yml

Fixes an issue when including both legacy and non-legacy auth paths where it would give repeated operationId errors.

fix: change legacy auth operationIds to include "Legacy"

---

contracts/managed-functions.yml
contracts/ref/cloud.yml
contracts/svc/managed-functions.yml
src/svc/managed-functions/paths/functions_functionID_invoke.yml

Related to https://github.com/influxdata/influx-cli/issues/153
Adds a `200` response code designation to the `functions/{functionID}/invoke` path, with a default to being a server error.
This is being done to allow the CLI codegen to work properly for this path.

feat: add response code to managed functions invoke by id

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/account.yml

Part of [Quartz #4360](https://github.com/influxdata/quartz/pull/4859)
Adds definition for `DELETE /account` to Unity swagger. This API will allow a user to self-delete an account, as long as the account is `free` and there are no other users.

feat(unity): Add route for `DELETE /account`

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml
src/oss/paths/backup_kv.yml
src/oss/paths/restore_bucket_bucketID.yml

These routes will be deprecated as of OSS v2.1.0, but we include them here for completeness & to support codegen on the CLI side.

fix: add legacy backup/restore routes to OSS contract

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
scripts/reference.sh
src/common/_paths.yml
src/common/paths/ping.yml

The users of our client libraries (`java`, `python`, `ruby`, ...) wants to do three things with our libraries: `query`, `write` and check the status of InfluxDB.
The query and writes are fine, but the checking status by `/health` endpoint brings trouble because the mapping is different for `oss` and `cloud` version. For more info see - https://github.com/influxdata/influxdb/issues/19357
As a solution this PR expose the `/ping` endpoint which works correctly in OSS and also in Cloud.
- https://github.com/influxdata/influxdb-client-python/issues/211
- https://github.com/influxdata/influxdb-client-ruby/issues/56
- https://github.com/influxdata/influxdb/issues/19357
- https://github.com/influxdata/influxdb/pull/21723

feat: add ping endpoint

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
scripts/reference.sh
src/cloud.yml
src/cloud/paths/orgs_orgID_secrets_delete.yml
src/cloud/paths/orgs_orgID_secrets_secretID.yml
src/common/_paths.yml
src/oss.yml

This deprecates the `/orgs/{orgID}/secrets/delete` route and adds one to delete a single secret by id.

chore: add route to delete individual secret

---

contracts/priv/unity.yml
src/unity/schemas/User.yml

Quartz is removing the concept of onboarding state in preparation for multi-account. This removes the `onboardingState` field from the `User` schema that is being used for the Operator UI.

Remove onboardingState from User schema

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml
src/oss/paths/remotes.yml
src/oss/paths/remotes_remoteID.yml
src/oss/paths/remotes_remoteID_validate.yml
src/oss/schemas/RemoteConnection.yml
src/oss/schemas/RemoteConnectionCreationRequest.yml
src/oss/schemas/RemoteConnectionUpdateRequest.yml
src/oss/schemas/RemoteConnections.yml

Closes influxdata/influxdb#22202
Open-ish questions:

feat: add OSS APIs for managing remote connections

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/remotes.yml
src/oss/paths/remotes_remoteID.yml

After stubbing out the server-side, some adjustments occurred to me that I think will make our lives (and users') easier:
* Instead of _always_ having the `POST`/create endpoint validate the connection info, make it an either-or:
* `dryRun=true`: validate but don't save
* `dryRun=false` (or missing): save without validating
* Add the same logic to the update-remote endpoint
* Rename `dryRun` to `validate` for clarity (`dryRun` gives the impression that the logic is 1:1 except for the final step of persisting the info to the DB)
I think the ability to save/update without validation will be useful when users are automating a full setup of an OSS instance, and the remote(s) get created before the other end is ready to receive connections (i.e. when connecting to another OSS instance being …

feat: rename dryRun to validate, add to update endpoint for remotes

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/accounts.yml
src/unity/paths/accounts_default.yml
src/unity/paths/operator_accounts.yml
src/unity/schemas/Account.yml
src/unity/schemas/Accounts.yml
src/unity/schemas/AccountsDefaultRequest.yml

Adds APIs for getting a list of the current user's accounts and for allowing the user to select a different default account.
These endpoints won't be implemented in Quartz for a few sprints, but having them defined now will allow the UI team to mock them out and start building out the UI for this feature.
When the implementation starts in Quartz, we'll also move the `DELETE /account` endpoint to `DELETE /accounts/:id` for consistency. See https://github.com/influxdata/quartz/issues/5077.

feat(unity): add account-switching API

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/remotes.yml
src/oss/paths/remotes_remoteID.yml

The OpenAPI Specification defines the **description** of Response Object as a required field - https://swagger.io/specification/#response-object. 
The responses without description causes the fails of our client generator - https://app.circleci.com/pipelines/github/bonitoo-io/influxdb-clients-apigen/143/workflows/4f34b35f-a797-4774-8a30-e5fe3c809a63

fix: add description for responses in Remote API

---

.circleci/config.yml
contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
scripts/test-openapi.sh
src/cloud/paths/experimental_sampledata_buckets_members.yml
src/oss/schemas/ReplicationCreationRequest.yml
src/oss/schemas/ReplicationUpdateRequest.yml

Add CircleCi check to [validate](https://openapi-generator.tech/docs/usage/#validate) `oss.yml` and `cloud.yml` specification by `openapi-generator-cli`. This CircleCI check ensures that the `oss.yml` and `cloud.yml` can be used for openapi-generator.

feat: add OpenAPI validator to CI

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/backup_kv.yml

This PR improves the `GetBackupKV` operation description so that a generated typescript code pass linter checks without this complaint: 
```
/packages/apis/src/generated/BackupAPI.ts
28:109  warning  tsdoc-escape-greater-than: The ">" character should be escaped using a backslash to avoid confusion with an HTML tag  tsdoc/syntax
```
The issue could be possibly fixed in the typescript code generator, but this simple PR will serve the needs in a much easier way pls.

chore(GetBackupKV): improve doc of GetBackupKV

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/restore_kv.yml
src/oss/schemas/PostRestoreKVResponse.yml

During a full metadata update, the operator token used to access the database changes (it is part of the metadata). To handle this properly, we need to know the new token value after a successful restore.
See https://github.com/influxdata/influxdb/issues/20749 .

feat: restore kv responds with new token after metadata update

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/paths/notebooks_share_id.yml

Oats was generating `getNotebooksShare` fn for two different endpoints. We don't actively use this one, so I'm removing it for now so it doesn't block integration.

fix: remove conflicting endpoint

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/ReplicationCreationRequest.yml

The names used in the `required` field of the replication-creation schema didn't match the rest of the schema

fix: correct names used in replications API

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/ping.yml
src/oss/paths/health.yml
src/oss/paths/ready.yml

Using `/` causes codegen'd clients to generate routes like `//health`. Empty string generates the right thing.

fix: use empty string for OSS root-path server URL

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/ref/cloud.yml
src/cloud/schemas/MeasurementSchema.yml
src/cloud/schemas/MeasurementSchemaList.yml

This PR amends the `MeasurementSchema` entity to add the following properties:
* `orgID`,
* `bucketID`
NOTE that the Cloud 2.0 API already returns these values and therefore this PR is ensuring the public API and the spec agree.

fix: Add orgID and bucketID properties to the MeasurementSchema entity

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId_invites.yml

The `/invites` endpoint rate limits organization invite post requests and will return `429` ( too many requests ) once the limit is reached.

feat: add 429 to org invites

---

README.md
contracts/README.md

While a mega reference file is useful in some cases, it isn't entirely developer friendly when one wishes to generate a client library to interface with a portion of the api. This repository is organized in such a way that client generators can target individual services, with some exceptions. To avoid breaking older patterns, some larger files that define behaviors from several services still remain, namely [`cloud`](https://github.com/influxdata/openapi/blob/master/contracts/cloud.yml) and [`oss`](https://github.com/influxdata/openapi/blob/master/contracts/oss.yml). These ideally will be broken up into smaller, more granular service definitions (write, query, tasks, etc...) for the api consumer's benefit. We will still continue to aggregate a platform's offering into a single …

chore: update readme to clarify contracts and give examples

---

contracts/priv/unity.yml
src/unity/schemas/OperatorAccount.yml

For the purpose of multi-account, account names will be a required field for an account. The names need to be added to the Operator UI, so I added the `name` value from the `Account` as a property to the `OperatorAccount` schema in Unity.

feat(unity): add account name as property for operator account schema

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/_schemas.yml
src/common/paths/telegrafs.yml
src/common/paths/telegrafs_telegrafID.yml
src/common/schemas/TelegrafPluginRequest.yml

This adds the missing (likely due to it being considered legacy and intended for deprecation (according to comments in api code)) `plugins` field to the request definition used by a post and a put request to `/api/v2/telegrafs[/:id]`.

chore(telegrafs): add plugins as valid field in post/put payload

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/swaggerV1Compat.yml
src/cloud.yml
src/oss.yml

* Fixes auth (security) schemes in cloud, oss, and v1compat.
* Adds missing `db=` and `rp=` query params in v1compat `/query`.
* Adds tagging for navigation in v1compat API docs.

fix: v1compat and auth schemes

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
src/common/paths/write.yml

Moves the `application/json` above the `text/html` content type so that the openapi codegen tool used by `influx-cli` uses the correct struct type. With `text/html` appearing first, the error type was being initialized as a `string` rather than a `LineProtocolLengthError`. This should match the intent of https://github.com/influxdata/openapi/pull/242

chore: arrange write path response types so CLI codegen works correctly

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/swaggerV1Compat.yml
scripts/reference.sh
src/cloud.yml
src/common/paths/write.yml
src/oss.yml
src/oss/paths/config.yml
src/oss/paths/health.yml
src/oss/paths/metrics.yml

Part of https://github.com/influxdata/docs-v2/issues/2567, https://github.com/influxdata/docs-v2/issues/3527
Add `/metrics` path and documentation in OSS.
Cleanup.

feat(oss): Document /metrics path for OSS

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/CheckBase.yml

We use `oss.yml` to generate API in our clients - `java`, `c#`, `php`, `ruby`, ... If the `latestCompleted` property doesn't have specified type to `string` the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) generates `latestCompleted` with generic type `object`. 
```csharp
/// <summary>
/// Timestamp (in RFC3339 date/time format](https://datatracker.ietf.org/doc/html/rfc3339)) of the latest scheduled and completed run.
/// </summary>
/// <value>Timestamp (in RFC3339 date/time format](https://datatracker.ietf.org/doc/html/rfc3339)) of the latest scheduled and completed run.</value>
[DataMember(Name="latestCompleted", EmitDefaultValue=false)]
public object LatestCompleted { get; private set; }
``` 
```csharp
/// <summary>
/// Timestamp (in RFC3339 date/time …
```

fix: missing specified type for `latestCompleted` property

---

contracts/priv/cloud-priv.yml
src/cloud-priv.yml

Part of https://github.com/influxdata/idpe/issues/13542
Removes the `/v2private/tenants` endpoint. This was originally a temporary endpoint, and is no longer used. It will be removed from IDPE as well.

chore: remove v2private/tenant

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/ReplicationCreationRequest.yml
src/oss/schemas/ReplicationUpdateRequest.yml

Part of https://github.com/influxdata/influxdb/issues/23109
The default chosen here, being `168 * time.Hour` (or 1 week) is adapted from Hinted Handoff, where this feature already exists

feat: add max age field to replications create

---

contracts/priv/unity.yml
src/unity/paths/operator_accounts.yml
src/unity/paths/operator_orgs.yml

In influxdata/ui#4218, I'm adding a dropdown to filter accounts by type in the operator UI. To support this change, the Quartz APIs for getting accounts and orgs for the operator UI has been updated to take an optional parameter of `accountTypes`, which is a list of available types given from the UI.

feat: Add Account types to operator get accounts/orgs

---

contracts/priv/quartz-oem.yml
src/quartz-oem.yml
src/quartz/paths/orgUsers.yml

This adds a new endpoint for adding users to an organization. `POST /api/v2/orgs/:org_id/users` will receive a list of emails as strings.

✨ Add Users to OEM Org Endpoint

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/XYGeom.yml

see [ui#2651](https://github.com/influxdata/ui/issues/2651)
pr adds stepbefore and stepafter in XYGeom to expose options for line graphs

chore: add two options to xygeom

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/organization_default.yml

Since we are passing the organization we want to be the new default in the body, we do not need it in the path.
Verified that this does not through errors for the ui by running `make generate` in the openapi repo, and then `yarn generate-local` followed by `yarn lint` in the UI repo without issue.

chore: Remove orgId from path of org default endpoint

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/PostOrganizationRequest.yml

This adds an optional list of user's emails to the OEM Post Organization request body.

✨ Add `users` to create OEM Org endpoint

---

contracts/priv/cloud-priv.yml
src/cloud-priv.yml
src/cloud/paths/provision_delete.yml
src/cloud/schemas/ProvisionDeleteRequest.yml

Closes https://github.com/influxdata/openapi/issues/300
See discussion here: https://github.com/influxdata/quartz/discussions/6039
Adds the API definition for the new `POST api/v2private/provision/delete` endpoint, which will be used to completely delete an organization from IDPE.

feat: provision delete org endpoint

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/ref/cloud.yml
src/cloud/paths/tasks.yml

There has been an effort to support multiple changes on the server side for support of pagination, filtering, and sorting of tasks on the server side, to get away from doing that on the client side.
This PR adds some documentation for the parameters that were added for query on the API.

feat: add query parameters to tasks contract that fulfill the pagination, filtering, and sorting epic

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/tasks_taskID_runs_runID.yml

Changing the contract to communicate that cancelling task runs will not be allowed in Cloud once https://github.com/influxdata/idpe/issues/14307 is complete.

chore: deleting task runs returns 405 method not allowed in cloud

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml

When moving components over to legacy in #330, I mistakenly left out `Authorizations` in `oss.yml` (which would be a breaking change). This PR adds that component back.

Fix missing OSS Authorizations component

---

contracts/legacy.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/swaggerV1Compat.yml
src/legacy/schemas/InfluxqlJsonResponse.yml

The `error` field is missing for legacy query JSON responses, and `tags` and `partial` missing from the series response schema.

Add missing properties to InfluxQL JSON response

---

contracts/priv/quartz-oem.yml
src/quartz/paths/org.yml
src/quartz/schemas/Organization.yml
src/quartz/schemas/OrganizationWithToken.yml

We added the name field to the OEM orgs response in Quarz for the Multi-Org effort, and this updates the spec to match that. This also updates the spec for the other /orgs endpoints since they didn't match the existing behavior.

Update the OEM api /orgs endpoint to reflect Quartz

---

contracts/priv/unity.yml
src/unity/schemas/IdentityAccount.yml

This adds an `isUpgradeable` field to the Quartz identity endpoint spec.

feat: Add isUpgradeable field to Quartz identity endpoint

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/me.yml

IDPE's `/me` endpoint (`GetMe`) is able return a `401` status, but it is not reflected in the current path for `/me` (which reflects status codes `200` or `500` only). 
/me endpoint returning a `401` unauthorized status code
This adds `401` as a valid status code  so that we can acknowledge it in the API layer of the UI.

fix: add 401 status code to idpe /me

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/legacy.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/write.yml
src/legacy/paths/query.yml

- If request exceeds cardinality limit, Cloud returns 429 instead of 503.
https://github.com/influxdata/DAR/issues/304

fix: over cardinality status code

---

contracts/priv/cloud-priv.yml
src/cloud/paths/provision_user_delete.yml

The `TaskOption` of `"transfer"` _is_ actually now implemented. I forgot to remove this from the spec when I did https://github.com/influxdata/idpe/pull/14909, so this PR takes care of that oversight.

chore: remove provision/user/delete task transfer error

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud/tags.yml
src/common/paths/tasks.yml
src/common/paths/tasks_taskID.yml
src/common/schemas/Task.yml
src/common/schemas/TaskStatusType.yml
src/oss/tags.yml

- Remove `type` property from task schema.
- Add, cleanup descriptions.
- Document update, delete, and inactive run cancellations.
- Add Tasks tag description for UI.
(part of #406, #407)

docs: improve tasks_taskID. Use global error refs.

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/PostOrganizationRequest.yml

Reverts influxdata/openapi#305
We decided that we no longer need this behavior.

Revert "✨ Add `users` to create OEM Org endpoint"

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId_invites.yml

When a user is invited to an organization, but they already belong to the account of that organization, they will instead be automatically added to the organization without sending an invite. In this case, we'll return back their user to be added to the UI.

feat(ecommerce): Add user response to organization invite

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/me_password.yml
src/common/paths/users_userID_password.yml

Closes https://github.com/influxdata/idpe/issues/15092
Changing passwords is not supported through the InfluxDB Cloud API, and this PR updates the API docs for that.

chore: passwords API on cloud not supported

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/accounts_accountId_orgs.yml

part of https://github.com/influxdata/quartz/issues/6604
Adds endpoint for returning a list of Organizations for the given account. Returns the same payload as `/orgs`.

chore: Add endpoint for getting orgs by account

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud/paths/tasks.yml
src/common/paths/tasks.yml

In `tasks.yml`, the 400 response of the `PostTasks` operation has an incorrect `content/application/schema` tag structure that no other responses use. This has now been flattened and the `description`/`examples` tags moved up.

fix: removed incorrect schema tag in PostTasks 400 response to fix CLI codegen

---

contracts/priv/unity.yml
src/unity/schemas/BillingInfo.yml

Removes the `region` from the `BillingInfo` Schema. The region is no longer needed in a multi-org/account world and instead of fetching the region for the active org, we simply removed it.

chore(billing): Remove Region from BillingInfo

---

contracts/invocable-scripts.yml
contracts/ref/cloud.yml
contracts/svc/invocable-scripts.yml
src/svc/invocable-scripts/schemas/ScriptInvokeResponse.yml

The `openapi` specification doesn't specify the `type` in the `Example` object:
https://swagger.io/specification/#example-object
This breaks our generator to build the [influxdb-client-java](http://github.com/influxdata/influxdb-client-java), [influxdb-client-python](http://github.com/influxdata/influxdb-client-python), [influxdb-client-csharp](http://github.com/influxdata/influxdb-client-csharp)...
https://app.circleci.com/pipelines/github/bonitoo-io/influxdb-clients-apigen/665/workflows/c4342df9-0b86-4d43-9205-05c7f43b06b5
Caused by https://github.com/influxdata/openapi/pull/451

fix(invocable-scripts): `type` is not allowed in example object

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/ref/cloud.yml
src/cloud/paths/tasks.yml

A recent change to cloud added the ability to search for tasks by their referenced script id, this documents that change.

chore(cloud-tasks): document scriptID in task find parameters

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/Replication.yml
src/oss/schemas/ReplicationCreationRequest.yml
src/oss/schemas/ReplicationUpdateRequest.yml

Replications will now support passing a bucket-name as well as a bucket-id. This is to provide full support for replication to 1.x installations. Fixes https://github.com/influxdata/influxdb/issues/23550

feat: add replication-bucket-name to replication

---

.gitignore

`prettier` is auto-formatting the **.yml** files by updating the indentation of the whole file on every save. That is too opinionated. To stop this from happening and making large diffs, let users set their own prettier ignore rules via **.prettierignore** which does not need to be shared by everyone.

feat: allow users to set custom prettier ignore rules

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionParams.yml

Related Issue: https://github.com/influxdata/data-acquisition/issues/441
add `brokerCACert` and `authType` params as we need 4 params
1. `brokerCACert`
2. `brokerClientCert`
3. `brokerClientKey`

chore(nifi): add brokerCACert param to subscription params

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/orgs.yml
src/unity/schemas/OrganizationCreateRequest.yml
src/unity/schemas/OrganizationWithToken.yml

[Quartz #6659](https://github.com/influxdata/quartz/issues/6659)
In multi-org a user will be able to add an organization to an account in the UI. Due to redirects in the Quartz version of this API, we had to make a separate endpoint for this new feature. This endpoint (`POST /api/v2private`) requires `region`, `provider`, and `orgName` in the request. It will return a `201` with the new organization if successful, otherwise it will return one of the following errors: `400`, `401`, `409`, and `500`.

feat: Add `POST /api/v2private/orgs` to unity

---

contracts/priv/unity.yml
src/unity/paths/orgs.yml

We decided to change the `400` response to `422` for the new `POST /api/v2private/orgs` endpoint. This keeps in line with our other `v2private` endpoints.

chore(ecommerce): Change `400` to `422` for Create Org `v2private`

---

contracts/priv/unity.yml
src/unity/paths/orgs.yml

#505 
As requested following [PR 504](https://github.com/influxdata/openapi/pull/504), the descriptions for status returns on `POST /api/v2private/orgs` have been updated.

chore: Cleanup descriptions for `POST v2private/orgs`

---

contracts/svc/invocable-scripts-internal.yml
src/svc-invocable-scripts-internal.yml
src/svc/invocable-scripts-internal/paths/scripts_labels_remove.yml
src/svc/invocable-scripts-internal/paths/scripts_labels_update.yml
src/svc/invocable-scripts-internal/schemas/ScriptBulkRemoveLabelRequest.yml
src/svc/invocable-scripts-internal/schemas/ScriptBulkUpdateLabelRequest.yml

Closes https://github.com/influxdata/idpe/issues/15643
This PR adds the new API endpoints for the scripts service. These APIs are not exposed on the edge and is only called internally by other services. This means they don't belong inside the existing `svc-invocable-scripts.yml` file, so I've created a new folder under `src/svc` called `invocable-scripts-internal` to include the paths and the schemas. And this folder is not added to the `generate.sh` script so that it won't be published.

feat(scripts): bulk update/remove internal API endpoints

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId.yml

For multi-org, Quartz now checks for organization name conflicts within an account. It will return a `409` if a name is already in use. The path for `PATCH /api/v2private/orgs/{orgId}` has been updated to reflect that.

chore: add `409` to PATCH /api/v2private/orgs/orgId

---

contracts/priv/uiproxyd.yml
contracts/svc/uiproxyd.yml
src/svc-uiproxyd.yml
src/svc/uiproxyd/paths/quartzLoginUrl.yml

Adds the `quartz-login-url` route for sending an environment variable to the ui

feat(uiproxyd): add quartz-login-url route

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionParams.yml

Helps https://github.com/influxdata/data-acquisition/issues/464
Changes name of `certProvidedAt` to `brokerCertCreationDate` as we've done in the code already.
Adds `clientID` property to params and response in preparation for new feature.

chore(nifid): add clientID

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/users_userID_password.yml

Related to https://influxcommunity.slack.com/archives/CHQ5VG6F8/p1662739448171649
The `POST` operation for `/users/{userID}/password` is used by InfluxDB clients (for more info see https://github.com/influxdata/influxdb-client-python/pull/498) and with current `oss.yml` we can't update the user's password.
This PR change the contracts according to current OSS implementation:
- Remove `BasicAuth` from POST operation for `/users/{userID}/password`
- Add `PUT` operation for `/users/{userID}/password`
For more info see:
- https://github.com/influxdata/influxdb/blob/b0a0e734e0c46384499cdc1f08f2673b6a28ff98/tenant/http_server_user.go#L91
- https://github.com/influxdata/influx-cli/blob/3a593e718476d9e671b4a003679722c0b32dc47b/clients/user/user.go#L148

fix(user): POST operation for `/users/{userID}/password` doesn't require basic auth

---

contracts/priv/unity.yml
src/unity/schemas/Organization.yml

This field is no longer used by the UI, so is obsolete and can be removed.

chore(unity): remove obsolete isRegionBeta from Organization

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/allowances_org_create.yml
src/unity/schemas/Allowance.yml

Part of influxdata/quartz#6725
This introduces the concept of an "allowance": is the current user/org/account **allowed** to perform an operation? The response contains the answer to the question as well as additional information that allows a UI to show more useful information.
For now, all we need is a flag indicating whether a plan upgrade would allow an operation that is currently denied, but we can expand this in the future when/if it becomes necessary.
Implementation-wise, an allowance encapsulates any business logic around permitting an operation, including entitlements (aka plan limits) as well as (in the future) roles/permissions.
It also introduces the first allowance query we need for multi-org: can an organization be created?

feat(unity): add query for org creation allowance

---

contracts/priv/unity.yml
src/unity/paths/orgs.yml

Fixes the schema being used for the `POST /api/v2private/orgs` endpoint.

fix: Use `Organization` schema for create orgs response

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud.yml
src/common/paths/flags.yml
src/common/paths/signin.yml
src/oss.yml

- Fix /signin and Basic Auth example.
- Describe feature flags and use case for /api/v2/flags.
Closes #387

docs: fix Basic Auth examples, describe /api/v2/flags:

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/RemoteConnection.yml

Makes `remoteOrgID` not a required field as we support remote connections to 1.x/Enterprise, and this field is unnecessary for a connection to that type of instance

chore: make `remoteOrgID` not required for ENT connection

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/RemoteConnectionCreationRequest.yml

Fixes a missed change needed in #583

chore: fix required `remoteOrgID` in remote creation req

---

contracts/priv/unity.yml
src/unity/schemas/Allowance.yml
src/unity/schemas/UpgradeOption.yml

Part of influxdata/quartz#6725
Change the `allowance` payload to return an enum value for what particular upgrade is available rather than just a boolean flag indicating that there is an upgrade available.
This endpoint is not yet in use, so there was no need to change this in an incremental, backwards-compatible way.

feat(unity): convert upgrade option to enum

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/invocable-scripts.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/svc/invocable-scripts-internal.yml
contracts/svc/invocable-scripts.yml
src/common/paths/buckets.yml
src/common/paths/delete.yml
src/common/paths/query.yml
src/common/paths/stacks.yml
src/common/paths/write.yml
src/common/responses/BadRequestError.yml

- Revise descriptions for `org` and `orgID` parameters.
Part of my previous PR #574, splitting for sanity.

docs: cleanup org and orgID params in OSS and Cloud.

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/legacy.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/priv/cloud-priv.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud.yml
src/cloud/paths/authorizations.yml
src/common/_schemas.yml
src/common/paths/authorizations.yml
src/common/requestBody/examples/AuthorizationRequestExamples.yml
src/common/requestBody/examples/TaskRequestExamples.yml
src/common/schemas/AuthorizationPostRequest.yml
src/common/schemas/Resource.yml
src/oss.yml

- Move examples out of text and curl shell examples to request body examples. The interesting bits are in the data, not the command. Rapidoc will display the payload schema as well as examples we define, though Redoc doesn't for now.
- Style cleanup.
- Improve descriptions.
Split out of #574.

docs: move code samples to request examples, fix descriptions:

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud/schemas/User.yml
src/common/schemas/User.yml

This removes an apparent unused schema property from both cloud and oss.

chore: remove unfunctional property 'oauthID'

---

contracts/priv/unity.yml
src/unity/paths/account.yml
src/unity/paths/operator_accounts_accountId.yml
src/unity/paths/orgs_orgId_users_userId.yml

This updates some Quartz endpoints that return 405 errors to return 403 errors instead.
We were using `Method Not Allowed 405` responses for when a resource is not able to acted upon. I think these errors are better suited at `Forbidden 403`, because the HTTP method is accepted, but the action is not allowed for an internal reason.

chore(aim): Replace 405s with 403s

---

contracts/priv/unity.yml
src/unity/schemas/Cluster.yml
src/unity/schemas/OperatorRegion.yml

Part of influxdata/quartz#6988
We are eliminating the concept of a beta cluster going forward. This removes the flag from `Cluster` and `OperatorRegion`.
It is not currently used anywhere in the UI codebase (though there is some WIP that might reference it).

chore(unity): remove isBeta flag

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/invocable-scripts.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/svc/invocable-scripts.yml
src/cloud/paths/dashboards.yml
src/cloud/paths/measurements.yml
src/cloud/paths/measurements_measurementID.yml
src/cloud/paths/tasks.yml
src/cloud/paths/users.yml
src/common/paths/buckets.yml
src/common/paths/dashboards.yml
src/common/paths/query_suggestions.yml
src/common/paths/query_suggestions_name.yml
src/common/paths/stacks.yml
src/common/paths/users.yml
src/common/schemas/CheckBase.yml
src/common/schemas/LabelMapping.yml
src/common/schemas/NotificationEndpointBase.yml
src/common/schemas/NotificationRuleBase.yml
src/svc/invocable-scripts/paths/scripts.yml
src/svc/invocable-scripts/paths/scripts_scriptID_invoke.yml

- Style and format dashboard descriptions.
- Replace 'retrieve lists' with 'lists'.
- Fix links.
- Fix links to Flux docs.
- Replace code URLs with placeholders.

docs: cleanup misc descriptions:

---

contracts/priv/quartz-oem.yml
contracts/priv/unity.yml
src/quartz/paths/orgs.yml
src/unity/paths/orgs.yml

With the new Entitlements limits, the private and OEM org creation endpoints will soon be able to return `Forbidden 403` errors when the max org limit has been reached within an account.
_Sorry about the formatter 🙏_

chore(aim): Add 403 to Org Creation Endpoints

---

src/unity/paths/operator_accounts_accountId_entitlements.yml
src/unity/paths/operator_accounts_accountId_entitlements_entitlement_id.yml
src/unity/schemas/Entitlement.yml
src/unity/schemas/Entitlements.yml

For the entitlements epic, we recently added 3 endpoints to support getting entitlements, creating/updating overrides, and deleting entitlements.
`GET /accounts/:account_id/entitlements`
`POST /accounts/:account_id/entitlements/:id`
`DELETE /accounts/:account_id/entitlements/:id`

chore(aim): Add Operator Entitlements Endpoints

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/common/paths/tasks.yml

Caused by #591 
The `orgID` parameter should not be required for `GetTasks` because the OSS implementation is able to works without this: https://github.com/influxdata/influxdb/blob/a0f1184bb3eeb8a6f8fa1bbdb9898d41355ff67f/kv/task.go#L227
```console
curl -i -X GET http://localhost:8086/api/v2/tasks -H 'Authorization: Token my-token'
```
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.5.0
Date: Sun, 06 Nov 2022 19:49:37 GMT
Content-Length: 673
{"links":{"self":"/api/v2/tasks?limit=100"},"tasks":[{"links":{"labels":"/api/v2/tasks/0a3f9de5d9a2e000/labels","logs":"/api/v2/tasks/0a3f9de5d9a2e000/logs","members":"/api/v2/tasks/0a3f9de5d9a2e000/members","owners":"/api/v2/tasks/0a3f9de5d9a2e000/owners","runs":"/api/v2/tasks/0a3f9de5d9a …
```

fix(tasks): `orgID` should not be required for `GetTasks`

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/ref/cloud.yml
src/cloud/paths/measurements.yml
src/cloud/paths/measurements_measurementID.yml

The request body should be marked as a required. Without required the `OpenAPI` generator allow creates request without body which causes InfluxDB error: 
```
>>> Request: 'POST https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/buckets/7100bd8a60da51ca/schema/measurements?orgID=04014de4ed590000'
>>> Accept: application/json
>>> Content-Type: application/json
>>> Authorization: ***
>>> User-Agent: influxdb-client-python/1.34.0dev0
>>> Body: None
```
```
<<< Response: 400
<<< Date: Sun, 06 Nov 2022 20:31:04 GMT
<<< Content-Type: application/json; charset=utf-8
<<< Content-Length: 67
<<< Connection: keep-alive
<<< trace-id: d86c9bd64c29c43d
<<< trace-sampled: false
<<< x-platform-error-code: invalid
<<< Strict-Transport-Security: max-age=15724800; includeSubDomains
<<< …
```

fix(bucket schemas): `requestBody` for `createMeasurementSchema` and `updateMeasurementSchema` should be required

---

contracts/priv/unity.yml
src/unity/paths/operator_orgs_orgId_limits.yml
src/unity/paths/orgs_orgId_invites.yml

This adds a forbidden error response the the `PUT /operator/orgs/{orgId}/limits` and `POST /orgs/{orgId}/invites` quartz endpoints.

chore: add forbidden error to quartz endpoints

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId.yml

As part of Multi-Org, this adds a private api endpoint for deleting orgs. This feature is limited to PAYG and contract accounts.

chore(aim): Add private delete org endpoint

---

contracts/priv/unity.yml
src/unity/schemas/OperatorOrganization.yml

This adds the `state` property to the `OperatorOrganization` schema.

chore: add state property to OperatorOrganization

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud.yml
src/common/paths/signin.yml
src/common/paths/signout.yml
src/oss.yml

- Restore link to Mozilla HTTP authentication doc.
- Add description and example for /api/v2/signout, expiring a user session (Closes #375).

Describe /signout

---

contracts/priv/unity.yml
src/unity/schemas/OperatorOrganization.yml
src/unity/schemas/Organization.yml
src/unity/schemas/OrganizationState.yml
src/unity/schemas/OrganizationSummary.yml

Adds an `OrganizationState` enum and the org state property to the endpoints that return orgs.

chore(aim): Add Org State to unity routes

---

contracts/priv/unity.yml
src/unity/paths/operator_orgs_orgId_reactivate.yml

When I added the org reactivate endpoint in #618, I didn't realize Oats would need the content type for an empty body still. This adds that back in so that the `unityRoutes` file gets generated correctly.

fix(aim): Add `content-type` to reactivate org endpoint

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId.yml

Similar to #620, this adds content type to the delete orgs endpoint, which is necessary for OATS to generate the correct unity routes.

fix(aim): Add `Content-Type` to delete orgs endpoint

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/priv/cloud-priv.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/Organization.yml

api/v2/orgs (the IDPE orgs endpoint) can send back a `defaultStorageType` property that discloses whether the org is using tsm or iox. This PR adds that optional property to the openapi spec.

chore: add defaultStorageType to organization

---

contracts/priv/unity.yml
src/unity/paths/orgs_orgId_users_userId.yml

When deleting a user, we will include the option to transfer the user's IDPE data to another user. This adds an optional parameter to the request body to provide a transfer's IDPE ID.

chore(aim): Add IDPE ID to transfer removed user's data to

---

contracts/priv/unity.yml
src/unity/schemas/TimeRange.yml

Part of #[7238](https://github.com/influxdata/quartz/issues/7238)
This PR updates the `timerange` options for usage information to reflect the latest changes in the system. The endpoint now supports a larger range of `timerange` options, from 1 day (1d or ~24h) to 30 days (30d).

feat: update timerange options for usage

---

contracts/invocable-scripts.yml
contracts/ref/cloud.yml
contracts/svc/invocable-scripts.yml
src/svc/invocable-scripts/schemas/ScriptLanguage.yml

Part of https://github.com/influxdata/ui/issues/6730
InfluxQL is supported in idpe invocable scripts https://github.com/influxdata/idpe/pull/17768, so updating the enum definition here.
I mainly updated one file `src/svc/invocable-scripts/schemas/ScriptLanguage.yml`. The rest of the files under `contracts` are auto generated from following the instruction [here](https://github.com/influxdata/openapi#how-to-contribute).
Similar to the work done for SQL in https://github.com/influxdata/openapi/pull/578.

chore: add influxql support to the yml

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/operator_accounts_accountId_reactivate.yml

In #642 I missed adding the route to the `unity.yml` file as well as forgot that oats requires the request body, even if blank. This fixes both.

fix(quartz): Add Reactivate Accounts to Unity

---

contracts/legacy.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
contracts/swaggerV1Compat.yml
src/legacy/paths/query.yml
src/legacy/schemas/InfluxqlJsonResponse.yml

Closes #650, part of https://github.com/influxdata/DAR/issues/424
- Add descriptions for InfluxQL JSON response properties.
-  Add example chunked response
- Fix: `Transfer-Encoding` header to schema (for chunked responses).
- Fix: add missing `partial` property to `results` schema.

fix: add missing `partial` and schema descriptions for InfluxQL JSON response
