contracts/managed-functions.yml
scripts/generate.sh

ports work from influxdata/ui#1313

chore: update managedFunctions swagger to match ui expectations

---

contracts/cli.yml
src/cli.yml
src/cli/paths/query.yml
src/common/schemas/OptionStatement.yml
src/common/schemas/VariableOrMemberAssignment.yml

I had to do some massaging of the existing ymls to make codegen happy, will comment inline with explanations.

feat(cli): add /query API to CLI contract

---

contracts/priv/notebooksd.yml
contracts/ref/oss.yml
contracts/svc/notebooksd.yml
scripts/generate.sh
src/svc-notebooksd.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows_id.yml
src/svc/notebooksd/paths/notebooks.yml
src/svc/notebooksd/paths/notebooks_id.yml
src/svc/notebooksd/requestBodies/NotebookParams.yml
src/svc/notebooksd/schemas/Notebook.yml
src/svc/notebooksd/schemas/NotebookArray.yml
src/svc/notebooksd/schemas/NotebookParams.yml
src/svc/notebooksd/schemas/Notebooks.yml

Adds the notebooksd service swagger definition. Hopefully I did it right 😅

feat: notebooksd svc

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows.yml

adding a missing param. only affects notebooksd

chore: add orgID param to /flows post

---

contracts/cli.yml
src/cli.yml

This isn't every API under `/org`, but it's all the CLI currently uses.

feat(cli): add remaining /org APIs needed for CLI codegen

---

contracts/cli.yml
contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/PostOrganizationRequest.yml

fix: fix indentation for PostOrganizationRequest

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/common/paths/users.yml

Both OSS and Cloud implement filtering on these parameters.

Add missing parameters to users API

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/tasks_taskID_runs_runID_retry.yml

fix(tasks): add content-type to task retry requests

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows_id.yml
src/svc/notebooksd/paths/notebooks.yml
src/svc/notebooksd/paths/notebooks_id.yml
src/svc/notebooksd/schemas/Notebook.yml

Made some minor changes to notebooksd swagger to be openapi v3 compliant

chore: update notebooksd swagger

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/payment_form.yml
src/unity/paths/usage_rate_limits.yml
src/unity/paths/usage_vector_name.yml
src/unity/schemas/Account.yml
src/unity/schemas/AccountType.yml
src/unity/schemas/Invite.yml
src/unity/schemas/Me.yml
src/unity/schemas/PaymentFormType.yml
src/unity/schemas/RelatedAccount.yml
src/unity/schemas/Role.yml
src/unity/schemas/TimeRange.yml
src/unity/schemas/User.yml
src/unity/schemas/VectorName.yml

An attempt to make the enums their own types since oats is having trouble setting the enum parameters as actual enums. Creating a universal ref for those so that it makes easier to understand the generated code

chore: made enums their own thing

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/BandViewProperties.yml
src/common/schemas/CheckViewProperties.yml
src/common/schemas/HeatmapViewProperties.yml
src/common/schemas/HistogramViewProperties.yml
src/common/schemas/LinePlusSingleStatProperties.yml
src/common/schemas/MosaicViewProperties.yml
src/common/schemas/ScatterViewProperties.yml
src/common/schemas/XYViewProperties.yml

Closes https://github.com/influxdata/ui/issues/1456
Adds a way to hide the tooltip independently of the static legend

feat: add legendHide for the tooltip

---

contracts/priv/unity.yml
src/unity/paths/cancel.yml
src/unity/paths/operator_account_accountId.yml
src/unity/paths/operator_account_accountId_users_userId.yml
src/unity/paths/orgs_orgId_invites.yml
src/unity/paths/orgs_orgId_invites_inviteId.yml
src/unity/paths/orgs_orgId_invites_inviteId_resend.yml
src/unity/paths/orgs_orgId_limits.yml
src/unity/paths/orgs_orgId_users_userId.yml
src/unity/schemas/Invite.yml

This PR cleans up the yaml a bit by syncing the data type with reality

chore: update the invite ID to be a number instead of a string

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
src/common/schemas/Query.yml

Adding the parameterized query definition to the query path on swagger

chore: add parameterized query definition

---

Makefile
contracts/ref/cloud.yml
contracts/ref/oss.yml
scripts/reference.sh

chore: add test for reference contracts to ensure generation

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows.yml
src/svc/notebooksd/paths/flows_orgs_orgID_flows_id.yml
src/svc/notebooksd/paths/notebooks.yml
src/svc/notebooksd/paths/notebooks_id.yml

- removes 405 responses
- adds 404 response to delete routes
- removes 400 response from "get all" routes

chore: notebooksd tweaks

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/operator_accounts_accountId.yml
src/unity/schemas/Accounts.yml
src/unity/schemas/Users.yml

Updating some schemas and definitions since oats was having a hard time

chore: updating some definitions that were getting compiled in funny ways

---

src/oss/paths/restore_bucket-metadata.yml

Remove param from restore API path.

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml
src/oss/paths/restore_bucket-metadata.yml
src/oss/paths/restore_kv.yml
src/oss/paths/restore_shards_shardID.yml
src/oss/paths/restore_sql.yml

Now that these are implemented on the server-side, add them to the API contract.

Add backup/restore routes to OSS contract.

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/operator_accounts.yml
src/unity/paths/operator_accounts_accountId.yml
src/unity/paths/operator_orgs_orgId.yml
src/unity/schemas/Account.yml
src/unity/schemas/Accounts.yml
src/unity/schemas/OperatorAccount.yml
src/unity/schemas/OperatorAccounts.yml
src/unity/schemas/Organization.yml
src/unity/schemas/Organizations.yml

This was being generated as type: any, this should fix that

chore: fix the accounts type

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/_schemas.yml
src/common/schemas/GeoPointMapViewLayer.yml
src/common/schemas/GeoViewProperties.yml
src/common/schemas/LatLonColumn.yml
src/common/schemas/LatLonColumns.yml

Adds new properties for customizing s2/lat/lon columns onto the GeoViewProperties.
Adds new properties for tooltip columns onto GeoLayerProperties

chore: add new properties for geo view

---

contracts/cloud.yml
contracts/common.yml
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/orgs_orgID_secrets.yml
src/common/paths/orgs_orgID_secrets_delete.yml

Removes the `Organizations` tag from Org Secrets yaml's

fix: remove Organizations from org secrets tags

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/common/schemas/Resource.yml

Removes the `nullable: true` line from `Resource` type parameter strings

refactor: remove `nullable` from `Resource` parameters

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/oss/paths/legacy_authorizations.yml
src/oss/paths/legacy_authorizations_authID.yml

Adds the token param for v1 auth get by ID path

feat: add token param to get v1 auth ID

---

contracts/oss-diff.yml
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml
src/oss/paths/legacy_authorizations.yml
src/oss/schemas/LegacyAuthorizationPostRequest.yml

Adds the token field to AuthorizationPostRequest. Also makes a `LegacyAuthorizationPostRequest` for v1 auth

feat: add token to v1 AuthPostRequest

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/Task.yml

chore: add ownerID definition

---

contracts/svc/pinneditemsd.yml
src/svc-pinneditemsd.yml
src/svc/pinneditemsd/paths/pinned.yml
src/svc/pinneditemsd/paths/pinned_id.yml
src/svc/pinneditemsd/requestBodies/PinnedItemParams.yml
src/svc/pinneditemsd/schemas/pinnedItem.yml
src/svc/pinneditemsd/schemas/pinnedItemArray.yml

feat: openapi routes for pinned items

---

contracts/priv/pinneditemsd.yml
scripts/generate.sh

Adds the definition for the routes in priv so we can point the route correctly in the UI package.json file

chore: add to priv

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/_paths.yml
src/common/paths/resources.yml
src/common/schemas/Resources.yml

link: https://github.com/influxdata/influxdb/pull/22135

feat: document new route to return known resources

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/priv/cloud-priv.yml
contracts/ref/cloud.yml
src/cloud/schemas/Limit.yml

Include delete limit information.

feat(limits-api): Update objects for limits api response.

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml
src/oss/paths/replications.yml
src/oss/paths/replications_replicationID.yml
src/oss/paths/replications_replicationID_validate.yml
src/oss/schemas/Replication.yml
src/oss/schemas/ReplicationCreationRequest.yml
src/oss/schemas/ReplicationUpdateRequest.yml
src/oss/schemas/Replications.yml

Closes influxdata/influxdb#22163

feat: add OSS APIs for managing replications

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc-notebooksd.yml
src/svc/notebooksd/paths/api_share_id.yml
src/svc/notebooksd/paths/api_share_id_query_pipeid.yml
src/svc/notebooksd/paths/notebooks_share.yml
src/svc/notebooksd/paths/notebooks_share_id.yml
src/svc/notebooksd/requestBodies/ShareParams.yml
src/svc/notebooksd/schemas/Share.yml
src/svc/notebooksd/schemas/ShareParams.yml
src/svc/notebooksd/schemas/Shares.yml

Adds new routes for notebooksd

chore: notebooksd new routes

---

contracts/managed-functions.yml
contracts/ref/cloud.yml
scripts/generate.sh

This removes cruft from an apparently old test
closes #206

fix: remove 'poc-' prefix from functions definition

---

src/oss/schemas/Replication.yml
src/oss/schemas/ReplicationCreationRequest.yml
src/oss/schemas/ReplicationUpdateRequest.yml

Part of https://github.com/influxdata/influxdb/issues/22880

feat: add dropNonRetryableData property to replications

---

contracts/priv/fluxdocsd.yml
contracts/svc/fluxdocsd.yml
scripts/generate.sh
src/svc-fluxdocsd.yml
src/svc/fluxdocsd/paths/fluxdocs.yml
src/svc/fluxdocsd/paths/fluxdocs_id.yml
src/svc/fluxdocsd/requestBodies/FluxdocsParams.yml
src/svc/fluxdocsd/schemas/fluxdocs.yml
src/svc/fluxdocsd/schemas/fluxdocsArray.yml
src/svc/fluxdocsd/schemas/fluxdocsParameters.yml

Closes https://github.com/influxdata/ui/issues/3180  
Closes #247 
Here is the initial definition. This will likely end up changing as routes are removed in the future.

feat: add api for fluxdocsd

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/account.yml
src/unity/paths/accounts_accountId.yml
src/unity/schemas/Account.yml
src/unity/schemas/AccountUpdate.yml

Part of influxdata/quartz#5077.
Adds a PATCH to update an account name.

feat(unity): add/update account operations

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/ColorMapping.yml

closes: https://github.com/influxdata/openapi/issues/256
depends on: https://github.com/influxdata/idpe/pull/12685
Minor update to the definition.

feat: update colorMapping property definitions

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss.yml

Uncomments the appropriate sections since remotes & replications are now on by default in OSS.

feat: enable remotes/replications resources for OSS

---

contracts/priv/unity.yml
src/unity/schemas/Me.yml

Part of influxdata/quartz#5813

Add clusterHost, regionCode and regionName for Me

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/paths/notebooks_id_versions.yml

The API just returns 200 for everything

chore: make it a 200

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc/notebooksd/schemas/Share.yml
src/svc/notebooksd/schemas/ShareParams.yml

Removed token from `POST` and removed `PUT` route from notebooksd. Need to remove token from openapi request/response bodies.

chore: remove token from response/request bodies.

---

contracts/svc/nifid.yml
src/svc/nifid/paths/broker_sub.yml

The status code from the POST endpoint in nifid returns 201, not 200

fix(nifid): correct create status code

---

contracts/priv/fluxdocsd.yml
contracts/svc/fluxdocsd.yml
src/svc-fluxdocsd.yml
src/svc/fluxdocsd/paths/fluxdocs.yml
src/svc/fluxdocsd/paths/fluxdocs_search_searchTerm.yml

Follow-on to https://github.com/influxdata/ui/issues/3180 - we updated the routes to only the ones that should be used

fix: update fluxdocs api with correct routes

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
scripts/reference.sh
src/oss.yml
src/oss/paths/debug_pprof_all.yml
src/oss/paths/debug_pprof_allocs.yml
src/oss/paths/debug_pprof_block.yml
src/oss/paths/debug_pprof_cmdline.yml
src/oss/paths/debug_pprof_goroutine.yml
src/oss/paths/debug_pprof_heap.yml
src/oss/paths/debug_pprof_mutex.yml
src/oss/paths/debug_pprof_profile.yml
src/oss/paths/debug_pprof_threadcreate.yml
src/oss/paths/debug_pprof_trace.yml

Closes #275
Add `/debug/pprof` paths for OSS.

feat: add debug/pprof paths for OSS.

---

contracts/priv/nifid.yml
scripts/generate.sh

Helps with https://github.com/influxdata/data-acquisition/issues/96
We need the /api/v2private file for nifid -  needed to add to generate script

fix: (nifid) add missing private file

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionStatus.yml

Helps https://github.com/influxdata/data-acquisition/issues/166
See https://github.com/influxdata/idpe/pull/13649 for context

chore(nifid): add isActive property

---

contracts/priv/notebooksd.yml
contracts/svc/notebooksd.yml
src/svc-notebooksd.yml
src/svc/notebooksd/paths/notebooks_id_clone.yml
src/svc/notebooksd/paths/notebooks_id_versions_id.yml
src/svc/notebooksd/schemas/NotebookVersion.yml

This PR adds the clone path for API notebook cloning and updates the yml definition for the return type of a notebook version

chore: initial stab at updating the openAPI yml

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/identity.yml
src/unity/schemas/Identity.yml
src/unity/schemas/IdentityAccount.yml
src/unity/schemas/IdentityOrganization.yml
src/unity/schemas/IdentityUser.yml

This adds the Quartz `GET /api/v2private/identity` spec.

Add Quartz `GET /identity` endpoint spec

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/SubscriptionParams.yml

Adds `inActive` param to subscription request

chore(nifid): inactive param

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/organization_default.yml
src/unity/schemas/OrganizationDefaultRequest.yml

Sets the default organization for a user.

chore: Add Default Organization PUT

---

contracts/priv/quartz-oem.yml
src/quartz/paths/orgUsers.yml
src/quartz/schemas/User.yml
src/quartz/schemas/Users.yml

This adds an endpoint to get users belonging to an organization.

✨ Add Get Organization Users Endpoint

---

contracts/priv/unity.yml
src/unity/paths/organization_default.yml

Add missing parameter definition to new route.

fix(unity): add missing parameter to /orgs/:orgId/default

---

contracts/priv/unity.yml
src/unity/paths/accounts_accountId.yml

This updates the `PATCH /accounts/{accountId}` spec to use the new `Account` schema.

Update account patch to use new Account schema

---

contracts/svc/uiproxyd.yml
contracts/uiproxyd.yml
src/svc-uiproxyd.yml
src/svc/uiproxyd/paths/sfdcSupport.yml
src/svc/uiproxyd/requestBodies/SFDCSupportParams.yml
src/svc/uiproxyd/schemas/SFDCSupport.yml

Adds `POST sfdc-support` to `uiproxyd`

feat(uiproxyd): add path for posting to sfdc-support

---

contracts/priv/uiproxyd.yml
contracts/svc/uiproxyd.yml
scripts/generate.sh
src/svc-uiproxyd.yml

This change makes openapi match the k8s-idpe service route

chore(uiproxyd): update url from /api/v2/maps to api/v2private/uiproxy

---

contracts/legacy.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/legacy.yml
src/legacy/paths/write.yml

Adds the `\write` path to legacy.

Add legacy write to legacy API

---

contracts/priv/cloud-priv.yml
src/cloud-priv.yml
src/cloud/paths/provision_user_delete.yml
src/cloud/schemas/ProvisionUserDeleteRequest.yml

API specification for the `/api/v2private/provision/user/delete` endpoint.

feat: provision user delete endpoint

---

contracts/common.yml
contracts/oss.yml
contracts/ref/oss.yml
scripts/generate.sh

Bump OSS version in `generate.sh`.

chore: update OSS release version to 2.3

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionParams.yml

related: https://github.com/influxdata/data-acquisition/issues/204

chore: update nifid with timestamp precision

---

.gitignore
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/query.yml

Added cURL and response to api/v2/query

cURL and response for query

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/query_analyze.yml

- Improve description.
- Add request and response examples.
- Add code sample.
Closes #356
Opened a related issue #355 for response error headers.

docs: Description and examples for query/analyze:

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud/paths/tasks.yml
src/cloud/paths/tasks_taskID.yml
src/cloud/schemas/Task.yml
src/cloud/schemas/TaskCreateRequest.yml
src/cloud/tags.yml
src/common/paths/tasks.yml
src/common/paths/tasks_taskID.yml
src/common/schemas/Task.yml
src/common/schemas/TaskStatusType.yml
src/oss/tags.yml

- Applies the updated descriptions in tasks to the new cloud spec for
tasks.
- Merged from master.

Docs tasks cloud

---

contracts/priv/cloud-priv.yml
src/cloud-priv.yml
src/cloud/paths/provision_setup.yml
src/cloud/schemas/ProvisionSetupRequest.yml
src/cloud/schemas/ProvisionSetupResponse.yml

API documentation for the new `/api/v2private/provision/setup` endpoint.

feat: document new provision setup api

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/query_suggestions_name.yml
src/common/schemas/QuerySuggestionsNameSuccessResponse.yml

https://github.com/influxdata/openapi/issues/396

query retrieve suggestion name 

---

contracts/legacy.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/schemas/Resource.yml

OSS is introducing the concept of an `instance` type that allows an approved user full permissions to everything in the instance (including adding additional orgs, etc).

feat: add instance resource type for oss

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionParams.yml

no longer using this property
related https://github.com/influxdata/data-acquisition/issues/317

fix: remove qos

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/users_userId.yml
src/unity/schemas/User.yml
src/unity/schemas/UserPatchRequest.yml

This adds a new `PATCH /api/v2private/users/:userId` endpoint to update a user's first/last name.

feat: Add patch user endpoint spec

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/priv/cloud-priv.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/buckets_bucketID_members.yml
src/common/paths/buckets_bucketID_members_userID.yml
src/common/paths/buckets_bucketID_owners.yml
src/common/responses/example-responses/GetBucketsIDMembersSuccessResponse.yml
src/common/responses/example-responses/PostBucketsIDMembersSuccessResponse.yml
src/common/schemas/AddResourceMemberRequestBody.yml
src/common/schemas/UserResponse.yml

Add member to a bucket
Get all members of a bucket
Remove a user from a bucket

Feat: add get delete members to a bucket

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/cloud/paths/users.yml
src/common/paths/tasks_taskID_owners.yml
src/common/paths/users.yml
src/common/schemas/TelegramNotificationRuleBase.yml

docs(task owners): descriptions and examples for task owners and users.

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/clusters.yml
src/unity/schemas/Cluster.yml
src/unity/schemas/Clusters.yml

This adds a new endpoint spec to list the clusters that are available for the current identity.

feat: Add endpoint to list clusters

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/query_ast.yml

Fixes the cURL code sample request body.

fix(ast): incorrect example payload.

---

contracts/cloud.json
contracts/cloud.yml
contracts/common.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/cloud.yml
contracts/ref/oss.yml
src/common/paths/0slash.yml
src/common/paths/ping.yml

feat: ping and route

---

contracts/priv/nifid.yml
contracts/svc/nifid.yml
src/svc/nifid/schemas/Subscription.yml
src/svc/nifid/schemas/SubscriptionParams.yml

Helps https://github.com/influxdata/data-acquisition/issues/560

feat(nifid): add useSSL property

---

contracts/priv/unity.yml
src/unity/schemas/Cluster.yml

a few properties of `Cluster` entity need to be `boolean` instead of `string`.

chore: update clusters contract

---

contracts/invocable-scripts.yml
contracts/ref/cloud.yml
contracts/svc/invocable-scripts.yml
src/svc-invocable-scripts.yml
src/svc/invocable-scripts/paths/scripts_scriptID_params.yml
src/svc/invocable-scripts/schemas/Params.yml
src/svc/invocable-scripts/schemas/ScriptParamsResponse.yml

Add documentation for the params endpoint of invocable scripts.

chore(invocable-scripts): add /api/v2/scripts/SCRIPT_ID/params

---

contracts/priv/unity.yml
src/unity/schemas/IdentityAccount.yml

Adds the `availableUpgrade` enum to the `/identity` endpoint.

chore(aim): Add `availableUpgrade` to `/identity`

---

contracts/priv/unity.yml
src/unity.yml
src/unity/paths/operator_orgs_orgId_reactivate.yml

chore(aim): Add Operator Reactivate Endpoint

---

contracts/priv/unity.yml
src/unity/schemas/Organization.yml
src/unity/schemas/OrganizationSummary.yml

This adds an isSuspendable field to the unity Organization and OrganizationSummary schemas.

feat: add isSuspendable field to org responses

---

contracts/priv/unity.yml
src/unity/schemas/OperatorOrganization.yml
src/unity/schemas/StorageType.yml

Adds the storage type to operator organizations.

feat(aim): Add `StorageType` to Operator Organizations

---

contracts/priv/unity.yml
src/unity/schemas/Account.yml

This adds an isDeletable field to the unity Account schema.

feat: add isDeletable field to account response

---

contracts/oss-diff.yml
contracts/oss.json
contracts/oss.yml
contracts/ref/oss.yml
src/oss/schemas/Replication.yml

Docs changes for https://github.com/influxdata/influxdb/pull/24126

feat: update replication field names to match influx changes

---

contracts/priv/unity.yml
src/unity/schemas/OperatorAccount.yml

Adding a new `cancellable` field to the operator account object

feat: Add cancellable attribute to the operator account object

---

contracts/cloud-diff.yml
contracts/cloud.json
contracts/cloud.yml
contracts/priv/cloud-priv.yml
contracts/ref/cloud.yml
src/cloud/schemas/Limit.yml

Add the new ioxQuery limit to the cloud limit object definition.

feat: add ioxQuery limit to cloud definition
